sic_codes_raw: 'C:\Users\samad\Documents\KPMG PKYC\sic_codes_raw.csv'
sic_hieracrhy: 'C:\Users\samad\Documents\KPMG PKYC\sic_hierarchy.xlsx'
db:
  path: 'C:\Users\samad\Documents\KPMG PKYC'
  name: 'pkyc_demo_db.db'
  full: 'C:\Users\samad\Documents\KPMG PKYC\pkyc_demo_db.db'
entity_types: ['private_limited_company', 'llp', 'sole_trader', 'charity']